[package]
name = "trey"
description = "Writing V3000 CTfiles."
version = "0.2.0"
edition = "2021"
license = "MIT"
license_file = "LICENSE"
homepage = "https://github.com/metamolecular/trey/"
readme = "README.md"

[dependencies]
lyn = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
